version: '3.9'

services:
  redis:
    image: redis:7.0
    ports:
      - 6379:6379
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
